ZSH_CUSTOM=$HOME/.zsh

source $ZSH_CUSTOM/path.zsh

function exists() {
  command -v "$1" >/dev/null 2>&1
}

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="miker"

COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git dir_chomp_tab pyenv)

# lots of prompt stuff requires the version managers to be loaded
source $ZSH_CUSTOM/version_managers.zsh
source $ZSH/oh-my-zsh.sh

export PYENV_VIRTUALENV_VERBOSE_ACTIVATE=1
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export VIRTUAL_ENV_DISABLE_PROMPT=1
